// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SssqScheduledJobsColumns holds the columns for the "sssq_scheduled_jobs" table.
	SssqScheduledJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"Init", "Processing", "Successful", "Failed", "WaitRetry"}, Default: "Init"},
		{Name: "queue_name", Type: field.TypeString, Default: "default"},
		{Name: "ref_id", Type: field.TypeString},
		{Name: "priority", Type: field.TypeUint, Default: 0},
		{Name: "retry_times", Type: field.TypeUint, Default: 0},
		{Name: "body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "scheduled_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// SssqScheduledJobsTable holds the schema information for the "sssq_scheduled_jobs" table.
	SssqScheduledJobsTable = &schema.Table{
		Name:       "sssq_scheduled_jobs",
		Columns:    SssqScheduledJobsColumns,
		PrimaryKey: []*schema.Column{SssqScheduledJobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "job_status_scheduled_at",
				Unique:  false,
				Columns: []*schema.Column{SssqScheduledJobsColumns[3], SssqScheduledJobsColumns[10]},
			},
			{
				Name:    "job_ref_id_queue_name",
				Unique:  true,
				Columns: []*schema.Column{SssqScheduledJobsColumns[5], SssqScheduledJobsColumns[4]},
			},
			{
				Name:    "job_queue_name_finished_at",
				Unique:  false,
				Columns: []*schema.Column{SssqScheduledJobsColumns[4], SssqScheduledJobsColumns[11]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SssqScheduledJobsTable,
	}
)

func init() {
	SssqScheduledJobsTable.Annotation = &entsql.Annotation{
		Table: "sssq_scheduled_jobs",
	}
}
