// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/supersupersimple/queue/ent/job"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (jc *JobCreate) SetCreatedAt(t time.Time) *JobCreate {
	jc.mutation.SetCreatedAt(t)
	return jc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableCreatedAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetCreatedAt(*t)
	}
	return jc
}

// SetUpdatedAt sets the "updated_at" field.
func (jc *JobCreate) SetUpdatedAt(t time.Time) *JobCreate {
	jc.mutation.SetUpdatedAt(t)
	return jc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableUpdatedAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetUpdatedAt(*t)
	}
	return jc
}

// SetStatus sets the "status" field.
func (jc *JobCreate) SetStatus(j job.Status) *JobCreate {
	jc.mutation.SetStatus(j)
	return jc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (jc *JobCreate) SetNillableStatus(j *job.Status) *JobCreate {
	if j != nil {
		jc.SetStatus(*j)
	}
	return jc
}

// SetQueueName sets the "queue_name" field.
func (jc *JobCreate) SetQueueName(s string) *JobCreate {
	jc.mutation.SetQueueName(s)
	return jc
}

// SetNillableQueueName sets the "queue_name" field if the given value is not nil.
func (jc *JobCreate) SetNillableQueueName(s *string) *JobCreate {
	if s != nil {
		jc.SetQueueName(*s)
	}
	return jc
}

// SetRefID sets the "ref_id" field.
func (jc *JobCreate) SetRefID(s string) *JobCreate {
	jc.mutation.SetRefID(s)
	return jc
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (jc *JobCreate) SetNillableRefID(s *string) *JobCreate {
	if s != nil {
		jc.SetRefID(*s)
	}
	return jc
}

// SetPriority sets the "priority" field.
func (jc *JobCreate) SetPriority(u uint) *JobCreate {
	jc.mutation.SetPriority(u)
	return jc
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (jc *JobCreate) SetNillablePriority(u *uint) *JobCreate {
	if u != nil {
		jc.SetPriority(*u)
	}
	return jc
}

// SetRetryTimes sets the "retry_times" field.
func (jc *JobCreate) SetRetryTimes(u uint) *JobCreate {
	jc.mutation.SetRetryTimes(u)
	return jc
}

// SetNillableRetryTimes sets the "retry_times" field if the given value is not nil.
func (jc *JobCreate) SetNillableRetryTimes(u *uint) *JobCreate {
	if u != nil {
		jc.SetRetryTimes(*u)
	}
	return jc
}

// SetBody sets the "body" field.
func (jc *JobCreate) SetBody(s string) *JobCreate {
	jc.mutation.SetBody(s)
	return jc
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (jc *JobCreate) SetNillableBody(s *string) *JobCreate {
	if s != nil {
		jc.SetBody(*s)
	}
	return jc
}

// SetError sets the "error" field.
func (jc *JobCreate) SetError(s string) *JobCreate {
	jc.mutation.SetError(s)
	return jc
}

// SetNillableError sets the "error" field if the given value is not nil.
func (jc *JobCreate) SetNillableError(s *string) *JobCreate {
	if s != nil {
		jc.SetError(*s)
	}
	return jc
}

// SetScheduledAt sets the "scheduled_at" field.
func (jc *JobCreate) SetScheduledAt(t time.Time) *JobCreate {
	jc.mutation.SetScheduledAt(t)
	return jc
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableScheduledAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetScheduledAt(*t)
	}
	return jc
}

// SetFinishedAt sets the "finished_at" field.
func (jc *JobCreate) SetFinishedAt(t time.Time) *JobCreate {
	jc.mutation.SetFinishedAt(t)
	return jc
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableFinishedAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetFinishedAt(*t)
	}
	return jc
}

// Mutation returns the JobMutation object of the builder.
func (jc *JobCreate) Mutation() *JobMutation {
	return jc.mutation
}

// Save creates the Job in the database.
func (jc *JobCreate) Save(ctx context.Context) (*Job, error) {
	jc.defaults()
	return withHooks(ctx, jc.sqlSave, jc.mutation, jc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jc *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := jc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jc *JobCreate) Exec(ctx context.Context) error {
	_, err := jc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jc *JobCreate) ExecX(ctx context.Context) {
	if err := jc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jc *JobCreate) defaults() {
	if _, ok := jc.mutation.CreatedAt(); !ok {
		v := job.DefaultCreatedAt()
		jc.mutation.SetCreatedAt(v)
	}
	if _, ok := jc.mutation.UpdatedAt(); !ok {
		v := job.DefaultUpdatedAt()
		jc.mutation.SetUpdatedAt(v)
	}
	if _, ok := jc.mutation.Status(); !ok {
		v := job.DefaultStatus
		jc.mutation.SetStatus(v)
	}
	if _, ok := jc.mutation.QueueName(); !ok {
		v := job.DefaultQueueName
		jc.mutation.SetQueueName(v)
	}
	if _, ok := jc.mutation.RefID(); !ok {
		v := job.DefaultRefID()
		jc.mutation.SetRefID(v)
	}
	if _, ok := jc.mutation.Priority(); !ok {
		v := job.DefaultPriority
		jc.mutation.SetPriority(v)
	}
	if _, ok := jc.mutation.RetryTimes(); !ok {
		v := job.DefaultRetryTimes
		jc.mutation.SetRetryTimes(v)
	}
	if _, ok := jc.mutation.ScheduledAt(); !ok {
		v := job.DefaultScheduledAt()
		jc.mutation.SetScheduledAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jc *JobCreate) check() error {
	if _, ok := jc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Job.created_at"`)}
	}
	if _, ok := jc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Job.updated_at"`)}
	}
	if _, ok := jc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Job.status"`)}
	}
	if v, ok := jc.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	if _, ok := jc.mutation.QueueName(); !ok {
		return &ValidationError{Name: "queue_name", err: errors.New(`ent: missing required field "Job.queue_name"`)}
	}
	if _, ok := jc.mutation.RefID(); !ok {
		return &ValidationError{Name: "ref_id", err: errors.New(`ent: missing required field "Job.ref_id"`)}
	}
	if _, ok := jc.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Job.priority"`)}
	}
	if _, ok := jc.mutation.RetryTimes(); !ok {
		return &ValidationError{Name: "retry_times", err: errors.New(`ent: missing required field "Job.retry_times"`)}
	}
	if _, ok := jc.mutation.ScheduledAt(); !ok {
		return &ValidationError{Name: "scheduled_at", err: errors.New(`ent: missing required field "Job.scheduled_at"`)}
	}
	return nil
}

func (jc *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := jc.check(); err != nil {
		return nil, err
	}
	_node, _spec := jc.createSpec()
	if err := sqlgraph.CreateNode(ctx, jc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = uint64(id)
	jc.mutation.id = &_node.ID
	jc.mutation.done = true
	return _node, nil
}

func (jc *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: jc.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUint64))
	)
	if value, ok := jc.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := jc.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := jc.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := jc.mutation.QueueName(); ok {
		_spec.SetField(job.FieldQueueName, field.TypeString, value)
		_node.QueueName = value
	}
	if value, ok := jc.mutation.RefID(); ok {
		_spec.SetField(job.FieldRefID, field.TypeString, value)
		_node.RefID = value
	}
	if value, ok := jc.mutation.Priority(); ok {
		_spec.SetField(job.FieldPriority, field.TypeUint, value)
		_node.Priority = value
	}
	if value, ok := jc.mutation.RetryTimes(); ok {
		_spec.SetField(job.FieldRetryTimes, field.TypeUint, value)
		_node.RetryTimes = value
	}
	if value, ok := jc.mutation.Body(); ok {
		_spec.SetField(job.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := jc.mutation.Error(); ok {
		_spec.SetField(job.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := jc.mutation.ScheduledAt(); ok {
		_spec.SetField(job.FieldScheduledAt, field.TypeTime, value)
		_node.ScheduledAt = value
	}
	if value, ok := jc.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (jcb *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if jcb.err != nil {
		return nil, jcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(jcb.builders))
	nodes := make([]*Job, len(jcb.builders))
	mutators := make([]Mutator, len(jcb.builders))
	for i := range jcb.builders {
		func(i int, root context.Context) {
			builder := jcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jcb *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := jcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jcb *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := jcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jcb *JobCreateBulk) ExecX(ctx context.Context) {
	if err := jcb.Exec(ctx); err != nil {
		panic(err)
	}
}
