// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/supersupersimple/queue/ent/job"
	"github.com/supersupersimple/queue/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[0].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
	// jobDescUpdatedAt is the schema descriptor for updated_at field.
	jobDescUpdatedAt := jobFields[1].Descriptor()
	// job.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	job.DefaultUpdatedAt = jobDescUpdatedAt.Default.(func() time.Time)
	// job.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	job.UpdateDefaultUpdatedAt = jobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// jobDescQueueName is the schema descriptor for queue_name field.
	jobDescQueueName := jobFields[3].Descriptor()
	// job.DefaultQueueName holds the default value on creation for the queue_name field.
	job.DefaultQueueName = jobDescQueueName.Default.(string)
	// jobDescRefID is the schema descriptor for ref_id field.
	jobDescRefID := jobFields[4].Descriptor()
	// job.DefaultRefID holds the default value on creation for the ref_id field.
	job.DefaultRefID = jobDescRefID.Default.(func() string)
	// jobDescPriority is the schema descriptor for priority field.
	jobDescPriority := jobFields[5].Descriptor()
	// job.DefaultPriority holds the default value on creation for the priority field.
	job.DefaultPriority = jobDescPriority.Default.(uint)
	// jobDescRetryTimes is the schema descriptor for retry_times field.
	jobDescRetryTimes := jobFields[6].Descriptor()
	// job.DefaultRetryTimes holds the default value on creation for the retry_times field.
	job.DefaultRetryTimes = jobDescRetryTimes.Default.(uint)
	// jobDescScheduledAt is the schema descriptor for scheduled_at field.
	jobDescScheduledAt := jobFields[9].Descriptor()
	// job.DefaultScheduledAt holds the default value on creation for the scheduled_at field.
	job.DefaultScheduledAt = jobDescScheduledAt.Default.(func() time.Time)
}
